# Regresión lineal en Python

## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/Users/Gullermo R/OneDrive/Documentos/GitHub/python-ml-course/datasets/ads/Advertising.csv")

In [3]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [4]:
X = data[feature_cols]
Y = data["Sales"]

In [5]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=2, step=1)
selector = selector.fit(X,Y)

In [6]:
selector.support_

array([ True,  True, False])

In [7]:
selector.ranking_

array([1, 1, 2])

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
X_pred = X[["TV", "Radio"]]

In [10]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [11]:
lm.intercept_

2.9210999124051362

In [12]:
lm.coef_

array([0.04575482, 0.18799423])

In [13]:
lm.score(X_pred, Y)

0.8971942610828956